### PR TITLE
Unified image

### PR DESCRIPTION
**Pull request by hexylena**
Simply run `docker run -it -p 8080:8080 erasche/apollo:unified` and a complete image with postgres and chado baked into the container will be available.

**Not recommended for production**

(Container is currently building)

### CODE REVIEW

**Comment by nathandunn** [comment]
Awesome thanks.   Looks like you fully dispensed with the env variables.

**Comment by nathandunn** [comment]
Unfortunately I ran  into this:  

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpq-dev : Depends: libssl-dev but it is not going to be installed
 npm : Depends: node-gyp (>= 0.10.9) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get -qq update --fix-missing && 	apt-get --no-install-recommends -y install 	git build-essential maven2 openjdk-7-jdk libpq-dev postgresql-common 	postgresql postgresql-client xmlstarlet netcat libpng12-dev 	zlib1g-dev libexpat1-dev ant perl5 curl ssl-cert nodejs npm && 	apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100
```

**Comment by hexylena** [comment]
Ok, will look into. That's odd though.

**Comment by nathandunn** [comment]
I'd ran into this bug earlier . . . needs to install a much more modern version of NPM / nodejs.   Usually just adding another source and its fine . . .  will post note here.

**Comment by hexylena** [comment]
@nathandunn if you're building locally, would you run `docker pull tomcat:7` first? This has built successfully on my machine and quay.io

**Comment by nathandunn** [comment]
@erasche  that worked.

**Comment by nathandunn** [comment]
Weird . . . any idea why (or if) there is a way to do it separately?

**Comment by hexylena** [comment]
Base image is cached. You can use the `--no-cache` flag when necessary, or just use the quay/docker hub built apollo images, and pull before use to ensure you have an updated copy.

**Pull request merged**
